[package]
name = "pinkdrone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.2"
winapi = { version = "0.3", features = ["memoryapi"] }
pretty-hex = "0.3"